### ISSUE TITLE
Never allow unwinding from Drop impls

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/lang-team#97]
# Summary

Code using `catch_unwind` is not typically prepared to handle an object that panics in its `Drop` impl. Even the standard library has had various bugs in this regard, and if the standard library doesn't consistently get it right, we can hardly expect others to do so.

This came up in @rust-lang/libs discussion.

We discussed various ways to handle this, including potential tweaks to `panic_any` or `catch_unwind` to add special handling of types that implement `Drop`, but on balance we felt like it would be preferable to decide at the language level to generally not allow unwind from `Drop` impls. (We may not be able to universally prohibit this, but we could work towards transitioning there.)

# Background reading

https://github.com/rust-lang/rust/issues/86027

# About this issue

This issue corresponds to a [lang-team design meeting proposal]. It corresponds
to a possible topic of discussion that may be scheduled for deeper discussion
during one of our design meetings.

[lang-team design meeting proposal]: https://lang-team.rust-lang.org/design-meeting.html

**Comment by joshtriplett** [comment]
To clarify something, I'm not proposing making a backwards-incompatible change here; there may well be code relying on the ability to do this. But there are steps we could take to deprecate this for new code, such as a new panic variant that allows unwind but not from Drop, which could eventually become the default. And eventually, *new* code may be able to safely say "this crate just doesn't support unwind-on-Drop at all".

**Comment by SimonSapin** [comment]
> And eventually, _new_ code may be able to safely say "this crate just doesn't support unwind-on-Drop at all".

Making a behavior change a property of the "current" crate is convenient to have opt-in through an edition, but what if multiple crates are involved? For example a generic function in edition A contains code expanded by a (proc-)macro in edition B that drops a value of a type parameter, which for a given instantiation is a type (and `Drop` impl) is in edition C.

**Comment by Lokathor** [comment]
Current panic behavior is universal, determined by the executable. There's never some crates with unwind and some with abort. This would have to be a third variant: unwind-but-not-in-drop.

**Comment by danielhenrymantilla** [comment]
Zulip discussion: https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/Never.20allow.20unwinding.20from.20Drop.20impls

**Comment by joshtriplett** [comment]
Notes from today's @rust-lang/lang design planning meeting:

    * For this meeting to be a success, we would need some exploration of what the alternatives are and what kinds of backwards compatibility concerns exist in the wild.
        * Are people relying on the current behavior?
        * Can we estimate how many latent bugs exist *because of* the current behavior?
            * Anecdotally: Rayon for example found it too hard to manage and just aborts.
            * Libs team has found this painful in the std library.

Current plan: defer this topic until a design meeting in August, plan for summarizing proposals and usage information from Zulip by that meeting.

**Comment by Amanieu** [comment]
I opened a PR which implements `-Z panic-in-drop=abort` (https://github.com/rust-lang/rust/pull/88759), we should have some perf results soon.

**Comment by Amanieu** [comment]
Initial perf results: up to 10% reduction in compilation time ([perf](https://perf.rust-lang.org/compare.html?start=c9db3e0fbc84d8409285698486375f080d361ef3&end=1f815a30705b7e96c149fc4fa88a98ca04e2deee)) and a 5MB (3%) reduction in the size of `librustc_driver.so`.

**Comment by nbdd0121** [comment]
Should there be finer-grain controls (e.g. type-level)?

**Comment by Amanieu** [comment]
> Should there be finer-grain controls (e.g. type-level)?

This would prevent us from optimizing drops of `Box<dyn Any>` since we wouldn't know whether they unwind.

I feel that this is best left as a global setting and that we eventually should enable it by default (and even remove the option of disabling it). This way authors of unsafe code can rely on stronger guarantees that dropping an object never unwinds.

**Comment by nbdd0121** [comment]
> This would prevent us from optimizing drops of `Box<dyn Any>` since we wouldn't know whether they unwind.

It's limited, but we can still perform some optimizations. E.g. if the drop to `Box<dyn Any>` is itself called from a nounwind function, we'll still abort rather than unwind.

> I feel that this is best left as a global setting and that we eventually should enable it by default (and even remove the option of disabling it). This way authors of unsafe code can rely on stronger guarantees that dropping an object never unwinds.

I believe there are still legit uses of panicking within drop. The stronger guarantee is usually about calling drop within drops; aborting in such scenario is more reasonable than a blanket "panic in drop will abort".

**Comment by Amanieu** [comment]
> I believe there are still legit uses of panicking within drop. The stronger guarantee is usually about calling drop within drops; aborting in such scenario is more reasonable than a blanket "panic in drop will abort".

I disagree: there are very few cases where panicking within drop is useful and there are huge benefits to removing these: not only do we improve compile times and binary size, but we also get rid of a footgun from the Rust language.

Consider that C++ (which is normally very conservative with breaking changes) made the same change in C++11: destructors were changed to be `noexcept` by default, which causes any exceptions which escape them to abort the process instead.

**Comment by nbdd0121** [comment]
Yes, they are `noexcept` *by default*, but there is still an escape hatch.

**Comment by nbdd0121** [comment]
I am concerned because it's easy to opt-in the nounwind behaviour, but it is difficult (or even impossible) to opt-out.

**Comment by Amanieu** [comment]
`-Zpanic-in-drop=abort` is now available and it provides significant improvements in binary size and compilation time, so I'd like to move forward with this discussion. There was some previous discussion in #14875 where some comments suggested leaving the door open for aborting in drops in the future.

It seems that the main concern is whether anyone is relying on the current behavior. I can see two main types of panic sources in drops:
- Assertions for things that should never happen, such as failures in `close`, `munmap`, `pthread_mutex_destroy`, etc. If any of these calls fail then something has gone *seriously* wrong (double-free?) and we are better off aborting immediately.
- Some APIs may run user-provided closures on drop. One example in the standard library is the unstable `drain_filter` API (#43244). This creates an iterator which returns items that were drained out of a collection, but will also eagerly continue draining to drop any remaining elements when the iterator is dropped. I would argue that this is a design mistake since `Iterator` is fundamentally designed around laziness.

Also I just came across #83618 which shows that properly handling panicking drops in unsafe code can be a huge footgun. That issue is about a bug in the standard library could lead to a double-free with a panicking drop.

**Comment by nikomatsakis** [comment]
@Amanieu if we were to schedule a design meeting for october, would you be available? 

Available times are:

* [October 13, 1pm Eastern time](https://everytimezone.com/s/940d7587)
* [October 20, 1pm Eastern time](https://everytimezone.com/s/79c9b836)
* [October 27, 1pm Eastern time](https://everytimezone.com/s/8eb42248)

**Comment by Amanieu** [comment]
I'm available on the 20th and 27th.

**Comment by Amanieu** [comment]
In https://github.com/rust-lang/rust/pull/92828 I improved the error message that is printed when an unwind tries to escape out of a `nounwind` function (`extern "C"`, `Drop` with `-Zpanic-in-drop=abort`, `#[rustc_allocator_nounwind]`, etc).

**Comment by Amanieu** [comment]
Looking through the various concerns and suggestions raised in this thread:

> My suggestion here is thus that we differ a bit from C++'s choice: while implicit calls to drop glue suffer from footguns similar to those of C++, and thus could be warranted the nounwind treatment, it makes little sense for drop(smth); to be a nounwind operation, especially considering that users could circumvent that limitation with a cumbersome ExplicitDrop trait akin to the definition posted above.

I think this use case is much better addressed by adding an explicit `close` method to the type you are trying to drop. For example, consider this API for `File`:

```rust
impl File {
	pub fn close(self) -> Result<()> {
		if libc::close(self.fd) != 0 {
			Err(errno)
		} else {
			Ok(())
		}
	}
}
impl Drop for File {
	fn drop(&mut self) {
		// Ignore errors
		libc::close(self.fd);
	}
}
```
If you want to catch errors that come from closing a file, use the `close` method. Otherwise if you don't care about errors (e.g. you're already unwinding due to a previous panic) then the `Drop` impl is used which ignores any errors (but still closes the file).

> I just want to bring up the idea of thread JoinHandles as well. Std JoinHandle detaches on drop, but join on drop is also a reasonable behavior to have.

IMO join on drop is best left for scoped threads (rust-lang/rfcs#3151) which can actually take advantage of the join with lifetimes. Also note that scoped thread will *not* propagate panics at the end of a scope if the parent thread is already unwinding.

> Scope guard would be an example where it runs an user-provided closure. I think it's unacceptable if panics within scope guards are forced to be unrecoverable.

This is unfortunate but I think this is a worthwhile tradeoff considering all of the gains from making `panic-on-drop=abort` the default behavior.

**Comment by Amanieu** [comment]
Here's how we could introduce this change in a release/

### No more unwinding from `Drop`

This release changes how panics behave when called from within a `Drop` implementation. Previously, a panicking `Drop` would behave differently depending on whether another panic was currently in the process of unwinding the stack.

- If it was, then the process was immediately aborted with a double-panic error.
- Otherwise, the panic would:
  - Skip the rest of the `Drop` impl.
  - Continue dropping the fields of the object with the panicking `Drop` impl.
  - If that object was itself part of a `struct`, array or `Vec` then the remaining fields/array elements are also dropped.

This behavior was non-obvious and error-prone. It has been the source of several security bugs in unsafe code both [inside](https://github.com/rust-lang/rust/issues/83618) and [outside](https://github.com/bluss/arrayvec/issues/3) the standard library.

In Rust 1.XX the behavior of panics in `Drop` has been changed to always abort the process. This mirrors a similar change made in C++11 where destructors terminate the process if an exception escapes them.

If you have any existing code which relies on panics in `Drop` not aborting the process, you should adjust your code to handle errors using a method that consumes `self`. For example consider this hypothetical `File` object:

```rust
struct File {
    fd: libc::c_int;
}

impl File {
    // Call this method to safely handle any errors from closing a file.
    pub fn close(self) -> std::io::Result<()> {
        if libc::close(self.fd) != 0 {
            Err(std::io::Error::last_os_error())
        } else {
            Ok(())
        }
    }
}

impl Drop for File {
    fn drop(&mut self) {
        // Errors are ignored when dropping. libc::close still closes the file
        // even if it returns an error.
        libc::close(self.fd);
    }
}
```

**Comment by joshtriplett** [comment]
I agree with @Amanieu's summaries here. I think we should evaluate the remaining questions as part of an FCP for a PR modifying the default.

**Comment by RalfJung** [comment]
I agree as well; some feedback on the release notes:

> In Rust 1.XX the behavior of panics in Drop has been changed to always abort the process. This mirrors a similar change made in C++11 where destructors terminate the process if an exception escapes them.

The word "escapes" here is curious -- it makes me wonder what happens when an exception is raised and caught inside a destructor, vs a panic that is triggered and caught in Rust. Is there any difference? (Yes, catching panics is discouraged, but it is still possible.)

**Comment by Amanieu** [comment]
If you catch the panic then it's not a problem. It's only panics that escape the drop that will abort. However it's very difficult to convey this detail in the wording, it's already quite confusing as it is.

**Comment by Lokathor** [comment]
is nounwind itself available as something a user can use? Perhaps in nightly only? we could link to those docs for further explanation.

**Comment by RalfJung** [comment]
> If you catch the panic then it's not a problem. It's only panics that escape the drop that will abort. However it's very difficult to convey this detail in the wording, it's already quite confusing as it is.

I would suggest having a short summary in the release notes, as you do, and then having an accompanying blog post that goes into all the details and discusses all these cases. That worked reasonably well in the past for other subtle changes, I think.

**Comment by Amanieu** [comment]
If you enable `#[feature(c_unwind)]` then `extern "C" fn` becomes nounwind. Alternatively there is `#[rustc_allocator_nounwind]` but that's an internal attribute with no docs. And `-Z panic-in-drop=abort` brings in `Drop` as a 3rd way to create nounwind functions.

**Comment by Lokathor** [comment]
Ah, but no simple `#[no_unwind]` attribute or similar that could collect the rules in an easy to find place.

**Comment by joshtriplett** [comment]
@Amanieu I think you could say something at the end (when talking about handling it) like "You can still catch a panic within a Drop implementation, as long as it doesn't unwind out of the Drop implementation."

**Comment by Diggsey** [comment]
I think the most opposition to this will come from projects where aborting is "very bad". For example, web servers which currently use `catch_unwind` on a per-request basis could easily have cases where something that would previously just cause the request to fail, now takes down the entire server, resulting in a new DoS attack vector.

It might be a good idea to introduce a couple of attribute macros, eg.

`#[suppress_double_panic]` and `#[suppress_and_log_panics]` which can be applied to legacy drop implementations as a stop-gap measure when upgrading such crates to whichever edition introduces this change.

**Comment by kpreid** [comment]
> ```rust
> impl File {
>     // Call this method to safely handle any errors from closing a file.
>     pub fn close(self) -> std::io::Result<()> {
>         if libc::close(self.fd) != 0 {
>             Err(std::io::Error::last_os_error())
>         } else {
>             Ok(())
>         }
>     }
> }
> 
> impl Drop for File {
>     fn drop(&mut self) {
>         // Errors are ignored when dropping. libc::close still closes the file
>         // even if it returns an error.
>         libc::close(self.fd);
>     }
> }
> ```

This implementation has a bug: `File::close()` calls `libc::close(self.fd)` and then drops `self`, causing `libc::close(self.fd)` to be called again, which might close an unrelated file that was opened on another thread in the time between the two closes. It needs to forget `self` (or use an `Option`, but that would add unnecessary costs).

This is just an example, of course, but making it correct and correctly explained will help illustrate how to correctly implement this explicit-close-or-drop pattern in general.

**Comment by Amanieu** [comment]
Thanks, fixed.

**Comment by adamreichold** [comment]
> For example consider this hypothetical File object:

One thing that was slightly irritating when reading this is that `std::fs::File` does not have such a `close` method. It has `sync_all` and documentation, but that takes `&self` and relies on implicit `Drop`.  I think that it would be nice if the standard library would follow these patterns at the time the default is changed.

**Comment by danielhenrymantilla** [comment]
Yeah that's an interesting point, especially when generalized: if this goes forward, there should still be a way to opt into dropping something while allowing interior panics/unwinding.

That is, imagine `File`'s close logic not having been featured yet as a standalone function (which can happen for third-party libraries out-there):

```rust
fn my_non_aborting_close(file: File) -> Result<(), …> {
    panic::drop_and_catch_unwind(file).map_err(|err| …)
    // or
    panic::catch_unwind(|| {
        mem::drop_with_unwinding_allowed(file);
    })
    .map_err(|err| …)
}
```

Btw, I already suggested this in https://github.com/rust-lang/lang-team/issues/97#issuecomment-953826053, named `drop_explicitly` —since, the issue to begin with is about *implicit drops being too terse*, so it seems overly restrictive to punish explicit code by *ricochet*, out of oversight?

___

So, if anything, before going forward, the case of _explicit_ drops ought to mentioned as well in this RFC / issue.

From there, the proposal would be rephrased as "never allow unwinding from implicit drops", where an "implicit drop of `x`" would be something that would not, transitively, call `drop_explicitly(x)` or `drop_with_unwinding_allowed(x)` or whatever that would be named.

  - With the remaining question of whether `drop(x);`'s implementation should remain unchanged (thus implicitly dropping `x`) or if it should be changed to calling `drop_explicitly` (I lean towards the former).

___

Finally, I would like to point out the code duplication of `close(self.fd)` in the snippets above: consider that this could be multi-line logic, and at that point properly factoring it out becomes:

```rust
/// internal logic factored out (private helper)
unsafe fn drop_thing(thing: &mut Thing) { … } // can panic

impl Drop for Thing {
    fn drop(self: &mut Thing) {
        let _ = unsafe { drop_thing(self) };
    }
}

impl Thing {
    fn drop_explicitly(self: Thing) { // can panic
        unsafe {
            drop_thing(&mut *ManuallyDrop::new(self))
        }
    }
}
```

That feels like a rather cumbersome thing to add to be able to allow callers to "call the drop glue in a way that allows unwinding".

**Comment by Amanieu** [comment]
Perhaps `File` is a bad example here. A better example is `BufWriter` in the standard library which already follows the pattern I suggested:
- The `flush` method returns an `io::Result<()>` which allows write errors from the underlying file to be caught and handled.
- The `Drop` impl for `BufWriter` simply calls `flush` and discards the `Result`.

---

> Btw, I already suggested this in https://github.com/rust-lang/lang-team/issues/97#issuecomment-953826053, named drop_explicitly —since, the issue to begin with is about implicit drops being too terse, so it seems overly restrictive to punish explicit code by ricochet, out of oversight?

I would argue that `explicit_drop` is almost never what you want. If there exists a possibility that dropping a resource might fail then this should be exposed using an explicit method (e.g. `close`, `flush`, etc).

Using `explicit_drop` would only be needed when interfacing with a badly designed API, but it would be better to handle this by fixing the API.

**Comment by kornelski** [comment]
I strongly dislike the proposed direction. I'm afraid that the end goal of complete removal of unwind in drop is too harsh, and loses important functionality in the language.

I do have the web-server use-case where `abort` is never acceptable. Even if the server is programmed to crash "gracefully" without data loss, it's still expensive to re-run server startup code, and to redo requests that were in flight. That can significantly hurt server's throughput and become a DoS vector.

Posix `close()` is useless, but there are other types of resources (transactions, guards) that need handling of errors when they're closing/dropping. Even if such resource has an explicit `close(self)` method, there's no way to guarantee such method is always used, because Rust doesn't have linear types. There still must be some fallback in `drop`. Panicking in `drop` is not great, but Rust doesn't have anything better.

Rust currently doesn't have any feature to give a compile-time guarantee there are no panics in `drop`, and this becomes much worse if there's no compile-time guarantee there are no aborts in `drop`.

So for me these factors add up to having weaker correctness guarantees, and harsher consequences of bugs in programs. I'd prefer the fix for `catch_unwind` to be more focused on the problem.

**Comment by joshtriplett** [comment]
@kornelski I agree in principle that we *should* have a way of handling failures in Drop. However, in practice, attempting to handle unwinding from Drop impls has been a massive footgun. The standard library has attempted to do so, and has on multiple occasions failed to get the details right, which really raises the question of whether it's reasonable to expect people to be able to get it right. Most libraries just don't attempt to handle that case at all.

For my part, I *also* care about the web server use case, and I don't plan to approve changing or stabilizing anything in this area until we have *some* strategy in place that allows for gracefully handling not just exit, but also other requests in flight (to the extent possible, given that the panicking code may be holding resources).

But that aside, the reason we're currently looking in this direction is effectively about *stronger* correctness guarantees: it's extremely hard to handle unwind-from-Drop correctly, and quite easy to get it wrong, and it's the kind of thing libraries should be able to opt *into* handling rather than being expected to handle by default. That doesn't mean we should take away all means of handling it, just that we shouldn't force *every* library in the Rust ecosystem to handle it or be considered incorrect.

**Comment by Diggsey** [comment]
> Even if such resource has an explicit close(self) method, there's no way to guarantee such method is always used, because Rust doesn't have linear types.

We already have lints like `#[must_use]`. I think we could easily lint against "closeable" things going out of scope normally. (They'd still need a destructor to handle going out of scope during unwinding though).

**Comment by Tamschi** [comment]
Two cents from me from an application point of view (I see this similarly to @kornelski and @danielhenrymantilla), if I may:

The nicest way for me to implement frontend component teardown, that is least error-prone to use and does not result in a large amount of boilerplate, is through the `Drop` implementation. Barring the availability of linear types (and good ecosystem support for them!), any workaround in this regard would cause a fairly large correctness pitfall for framework consumers.
(I can theoretically catch a lot of that with creative source code rewriting in a macro, but that's *considerably trickier* than making everything that drops instances as panic-aware as it needs to be.)

Panics from drops are not necessarily ideal, but even with improper handling, the errors they result in are in most cases safe resource leaks that are often nearly inconsequential for end user software, even if the error is only papered over at a high level. (It's not ideal of course, but a desktop application usually has to be *very* broken in this regard to crash from it or become unusable in a way that the user can't work around in a way that preserves their data.)
Conversely, these programs tend to be complex and not easily testable, and a hard crash is almost always the wrong outcome as long as you can guarantee the memory at least didn't get scrambled.

(My use case here is mostly creative end user software, where hard crashes are unfortunately common and often result in loss of work that can't be recreated precisely, unlike when e.g. an IDE or console application crashes.)

The only place where this becomes more difficult in my view are pinning containers, which really do need correct `drop`-caused-panic handling if they'd like to avoid shallow memory leaks. I'm concerned that, should more people start writing these and Rust default to aborting the process if a drop implementation panics, it would accidentally encourage incorrect *unsound* implementations of that code instead when abort-on-drop-panic is disabled through a compiler flag.

**Comment by Diggsey** [comment]
@Tamschi double panics already result in an abort. I'm not sure why component teardown would panic in your case, but it seems like if one component teardown panics, then attempting to teardown a different component (which would happen as a result of the first panic) may also panic, resulting in a process abort.

For code to avoid aborts in today's Rust, and also potentially panic, you need to use `is_panicking` in your destructor, and if true, avoid doing things that may cause a second panic. Avoiding panicking entirely results in simpler and less error prone code, even within the destructor.

**Comment by Tamschi** [comment]
> @Tamschi double panics already result in an abort. I'm not sure why component teardown would panic in your case, but it seems like if one component teardown panics, then attempting to teardown a different component (which would happen as a result of the first panic) may also panic, resulting in a process abort.
> 
> For code to avoid aborts in today's Rust, and also potentially panic, you need to use `is_panicking` in your destructor, and if true, avoid doing things that may cause a second panic. Avoiding panicking entirely results in simpler and less error prone code, even within the destructor.

The problem is that I can't do so at a framework level. I'd have to require each user component to do this correctly individually.
(It is reasonably easy to avoid double-panics in many circumstances, since component construction and teardown are much more regular.)
In light of that, if this change here goes through, I'd always enable unwinding from drop implementations via compiler flag (and do more thorough code reviews or my dependencies in that regard, I suppose…)

If aborts from drop implementation panics were to become unconditional, that would likely be a blocker for me for using Rust in larger projects, as harsh as it sounds. I just can't have a single erroneous component crash the whole app that easily.

**Comment by Tamschi** [comment]
> > Avoiding panicking entirely results in simpler and less error prone code, even within the destructor.
> 
> That could mask a bug while in case of running `Drop` on unwinding you already know there is a bug and thus suppressing another panic is fine and doesn't mask a bug.

I don't think that's necessarily a good idea, since this could mask an error that can't be handled behind one caught by `catch_unwind` somewhere. I'd prefer to see aggregate panics in such cases, if the second panic was suppressed implicitly.

That said, a solution that would work for me even if `drop`-panics unconditionally aborted would be if I could reliably forbid them for the entire application. I assume that would still require a lot of dependency rewrites to make them compatible with that, but that's much less of a problem than brittle end user applications.

**Comment by m-ou-se** [comment]
> I do have the web-server use-case where `abort` is never acceptable. [..]
>
> Posix `close()` is useless, but there are other types of resources (transactions, guards) that need handling of errors when they're closing/dropping.

Does that web server never run into situations where a Drop of such a type is caused by the unwinding of an already ongoing panic, which means a panic in that Drop would cause an abort? Do those types' Drop implementations all check `std::thread::panicking()` before doing anything that might panic?

**Comment by yaahc** [comment]
I'd be curious to look at examples of code that could use linear types instead of panic in drop to handle proper resource cleanup and error handling. My intuition is that our affine type system can in practice emulate the useful aspects of linear types for cases like this if you use a closure based API in the style of ghost cell / scoped threads, for example:

```rust
// you must call opened_resource.close() to get the Closed token that matches the branded lifetime
// you must return that token to compile
resource.use_with(|opened_resource: Resource<'resource>| -> ClosedToken<'resource> {
    ...
})
```

**Comment by RalfJung** [comment]
With a closure-based API, I would expect one would destroy the resource in `use_with` after the closure returns; then `use_with` itself can return a `Result` type to propagate possible error information. That would avoid the need for complicated lifetime trickery.

**Comment by Lokathor** [comment]
Winit uses a closure based API and everyone *hates* it. Even the winit people don't actually like it, they just have to do it that way to work properly in the browser.

**Comment by Tamschi** [comment]
> I'd be curious to look at examples of code that could use linear types instead of panic in drop to handle proper resource cleanup and error handling. My intuition is that our affine type system can in practice emulate the useful aspects of linear types for cases like this if you use a closure based API in the style of ghost cell / scoped threads, for example:
> 
> ```rust
> // you must call opened_resource.close() to get the Closed token that matches the branded lifetime
> // you must return that token to compile
> resource.use_with(|opened_resource: Resource<'resource>| -> ClosedToken<'resource> {
>     ...
> })
> ```

There are two scenarios that come to mind:

1. Any Wasm frontend, essentially, as the main thread needs to return entirely to JS before the page can be re-rendered. (There may be some ways to get around this with web workers and shared memory, but not without `unsafe` code to release lifetimes to share exclusive borrows through `static`s.)

2. Consider a UI that displays two tab groups, where individual tabs are (heavy and as such hold or discard resources as they're switched to or from, e.g. for native GUI controls). Allowing the user to switch between tabs independently would cause an interlaced `A B ~A ~B` resource acquisition pattern, which can't be modelled with closures.

It's still possible to do this with a closure-based API by instead having the closure provide a resource manager that all resources are then built around (so that any errors from discarding them can be stored), but this would silence individual errors until the application closes. (Though, in practice this does seem to be a common method of error handling, since I have a bunch of programs on my computer that crash specifically on shutdown.)

**Comment by ojeda** [comment]
> I think the standard library is a very unusual Rust "user", and experience from it is different than experience of mere application developers. libstd has be correct for **any** possible type, and gives soundness guarantees even in theoretical scenarios. My applications — in practice — only need to be correct for the few _actual_ types I'm using, and not crash (including abort!).

But it applies to libraries in general, though, not just `std` (except maybe for project-internal libraries which may be considered application code anyway). I read Josh's `std` mention as just an example where it happened.

**Comment by oxalica** [comment]
> > I think the standard library is a very unusual Rust "user", and experience from it is different than experience of mere application developers. libstd has be correct for **any** possible type, and gives soundness guarantees even in theoretical scenarios. My applications — in practice — only need to be correct for the few _actual_ types I'm using, and not crash (including abort!).
> 
> But it applies to libraries in general, though, not just `std` (except maybe for project-internal libraries which may be considered application code anyway). I read Josh's `std` mention as just an example where it happened.

Agree since my own library is reported to be caught by this issue. https://github.com/oxalica/async-ffi/issues/7
For FFI-related crates, catching panic is already an annoying thing. Especially when we are wrapping user provided closure in some FFI callbacks. Now we have to catch it twice: one for catching user panic, and another for catching user panic payload's Drop.

Remind: Whenever user code panics, if it causes a library to run into undefined behaviors, the user would absolutely blame the library, not themselves.

**Comment by yaahc** [comment]
Instead of using linear types which let us avoid drop completely, I feel like this could be solved if standard runtime error handling and drop were composable. I once again find myself wishing rust had an effects system :/

**Comment by bjorn3** [comment]
Maybe we can have a lint for implicit drop calls within unsafe blocks unless the drop impl is marked with an attribute to make panics abort? Said attribute could then be applied whenever a drop impl is known to never panic. For example when it only calls `libc::close` and ignores the error. Suppressing the lint can be done using `std::mem::drop(val)` which gives an explicit signal to the reviewer that a panic could happen at that point.

**Comment by Wurstbrotc5** [comment]
One more use case that would be helped with unwind in Drop: Coroutines.

if there is a panic "outside" of the coroutine, while it is paused, the object that manages it and allowed continuing gets dropped.
During drop, it might want to switch in and unwind things there, then switch back out to allow the panic to continue.

Please don't completely prevent this

**Comment by Diggsey** [comment]
@Wurstbrotc5 that would not be affected since this is about unwinding *from* Drop, not unwinding *within* Drop.

**Comment by CAD97** [comment]
Foreign unwind is already UB (currently). AIUI, at the LLVM level `nounwind` is a promise, not a guard like it is in C++.

When `extern "C-unwind"` lands and makes foreign unwinding not just instant UB, the drop shim should add an extra shim to catch whatever foreign unwinding is allowed.

**Comment by nbdd0121** [comment]
> Foreign unwind is already UB (currently). AIUI, at the LLVM level `nounwind` is a promise, not a guard like it is in C++.

We have `#[rustc_allocator_nounwind]` and `CodegenFnAttrs::NEVER_UNWIND`, and they work with `AbortUnwindingCalls` pass to actually provide a guarantee/guard.

**Comment by nbdd0121** [comment]
> The solution to prevent this footgun is simple enough, though it does use functionality not yet available: when `panic_any` is called, monomorphize a new vtable with `drop_in_place` replaced with a new shim that sets `thread::panicking` while dropping the panic payload[1](#user-content-fn-1-5878c948395dac9a38239739d797fbaa). This will cause a panic-in-panic-payload-drop to abort, and not impact any other panics. We can even specialize `panic_any` to not shim `&str` or `String` to avoid the extra vtables for the majority of cases.

Actually this idea wouldn't work because we have `resume_unwind` which takes an user-supplied `Box<dyn Any + Send>`.

**Comment by CAD97** [comment]
So the optimization to avoid extra vtables doesn't work, but [dtolnay's solution with a linked list of `dyn Any` vtables](https://github.com/rust-lang/rust/issues/86027#issuecomment-858083087) still works, and is currently my preferred solution.

**Comment by nbdd0121** [comment]
I think it's worth to note that the footgun of `catch_unwind` can be completely solved by making the caller of `catch_unwind` nounwind. 

Currently there are no ways to do so in stable Rust, but once `c_unwind` feature is stablised, any `extern "C"` function will automatically become nounwind and thus using `catch_unwind` inside such function will not have the footgun. This is likely sufficient for the FFI-related scenario pointed out by @oxalica and usage within Rust RT like lang_start_internal.

**Comment by CAD97** [comment]
However, the footgun still exists in `unsafe` code that needs to prevent unwinds from observing broken unsound state, such as [scoped threads](https://github.com/rust-lang/rust/pull/94644). The most common case is `extern "C"`, yes, but preventing unwinds is still relevant in pure-Rust code.

**Comment by Amanieu** [comment]
One point of view that I feel hasn't been discussed enough is the significant code size and compile-time improvements that we can get by making this change.

> Initial perf results: up to 10% reduction in compilation time ([perf](https://perf.rust-lang.org/compare.html?start=c9db3e0fbc84d8409285698486375f080d361ef3&end=1f815a30705b7e96c149fc4fa88a98ca04e2deee)) and a 5MB (3%) reduction in the size of `librustc_driver.so`.

I also got a 5% reduction in binary size (release, stripped) when building ripgrep:
```
-Z panic-in-drop=unwind: 4242864 bytes
-Z panic-in-drop=abort: 4033968 bytes
```

Looking at it another way: if the current Rust default was to abort when unwinding from a drop, would we be willing to pay a 5% binary size and 10% compile-time cost to support unwinding from drops? (And even then, only drops when not already unwinding)

I feel that this cost would be considered unacceptable for such a niche feature. Since this is one space where we are not bound by backwards-compatibility guarantees, I feel that this is a worthwhile change to make.

**Comment by CAD97** [comment]
> Since this is one space where we are not bound by backwards-compatibility guarantees,

I'm personally not really sold on this. (Though to be fair, I'm not someone that *needs* to be convinced.) Forbidding unwinding from `Drop::drop` isn't a soundness fix; the language level soundness fix is injecting a landing pad for nounwind contexts (e.g. `extern "C"` and `GlobalAlloc`) and the rest is (perhaps a long tail of) library fixes for collections. Unwinding from `drop` is generally considered a thing to avoid because it *could* abort even when panic=unwind, but it's still a useful tool to have[^1].

[^1]: As a small case study, I have a crate which involves doing an FFI call that could theoretically fail for resource cleanup on drop. If the library is used correctly and the FFI bindings don't have any bugs, then the call won't return an error. However, I still want to check the error, especially when `cfg(debug_assertions)` is true. As such, on drop, if the FFI resource cleanup call returns an error, I `log::error!` the error, and if `cfg!(debug_assertions) && !thread::unwinding()`, `panic!`. The goal is to abort the task to a `catch_unwind!` landing pad because something unexpectedly went wrong, but it's not so unrecoverable that aborting is appropriate.

Please forgive the slippery slope comparison, but saying forbidding unwinds from `Drop::drop` is a minor breaking change because panics in `drop` already could drop feels a step away from saying making library panics always abort because they already could either unwind or abort, because a consumer could call `panic::always_abort()`.

We allow use of `panic!`/`catch_unwind` for task-level aborts if the binary author sets `panic=unwind`. The argument which I'm trying to convince myself isn't just based on slippery slope FUD is that the reasoning in allowing this usage applies just as well to allowing unwinding from RAII `drop` if the developer knows that panic=unwind and the drop won't be called from a panicking code path.

> such a niche feature

I actively disagree with this assessment of unwinding from `drop`. While I agree that *intentional* unwinding from drop is a somewhat niche feature (though doing fallible finalization on drop may not uncommonly be written to `unwrap` instead of dropping the result), *running downstream code* from an RAII guard is imho *not* a niche feature.

I really don't want to ever have to say "this shouldn't be an RAII `defer!` (or equivalent) because it could panic; just put the code at the scope exit point (and hope we never add an early exit)." In fact I have [one bit of API](https://docs.rs/erasable/latest/erasable/struct.Thin.html#method.with_mut) which needs to run a user trait method on a user closure return or unwind for soundness, so I need to have an RAII guard, but if I want to propogate a panic if it's not an unwind, I'd need to duplicate the cleanup code out of the RAII guard for the happy path as well.

> One point of view that I feel hasn't been discussed enough is the significant code size and compile-time improvements that we can get by making this change.
>
> Looking at it another way: if the current Rust default was to abort when unwinding from a drop, would we be willing to pay a 5% binary size and 10% compile-time cost to support unwinding from drops?

We can still get the benefits, though, by adding a new `panic=unwind-not-from-drop` profile configuration. The default `panic=unwind` profile would be unaffected, and binaries which are confident that they don't unwind from drop but don't want to be `panic=abort` can set `panic=unwind-not-from-drop` for the size benefit.

There's already a position for code which is only sound with `panic=abort` (e.g. `take_mut` without an abort bomb) because it isn't unwind safe. It doesn't seem too farfetched to say that code which fails to account properly for drop unwinding is only sound when `panic=unwind-not-from-drop` (or `panic=abort`).

The one thing I'd personally want with that feature is a new function to compliment `thread::panicking()` which *just* tells you if a panic from drop would currently abort.

**Comment by joshtriplett** [comment]
I had previously raised the question of adding documentation for what patterns people should use to allow handling errors when closing a resource. @Amanieu discovered that apparently we have that documentation already: https://rust-lang.github.io/api-guidelines/dependability.html#destructors-never-fail-c-dtor-fail

Given that documentation, I'd like to gauge team consensus on the following narrow question:

Do we want to switch the default over to `panic-in-drop=abort`?

Note that this is *not* yet asking the question of whether we want to remove panic-in-drop=unwind, or add a stable option for it, or any other aspect of this change, only whether we want to switch the default.

@rfcbot merge

**Comment by CAD97** [comment]
(I'd like to note that that guideline doesn't specify what to do *instead* in the destructor if `close` isn't called. The most natural thing would be to (call `close` automatically and) panic due to the programmer error (not calling `close`). If the default is switched to panic-in-drop=abort, and probably just if panic-in-drop becomes a thing libraries are expected to support, then the guideline should be expanded to say that failing to call `close` should either leak the error from `close` or leak the unclosed resource (and potentially log a warning, if available).)

**Comment by RalfJung** [comment]
> Note that this is not yet asking the question of whether we want to remove panic-in-drop=unwind, or add a stable option for it, or any other aspect of this change, only whether we want to switch the default.

I am not sure I understand, but doesn't this effectively remove support for panic-in-drop=unwind on stable, where no flag is available to change the default?

**Comment by joshtriplett** [comment]
> (I'd like to note that that guideline doesn't specify what to do _instead_ in the destructor if `close` isn't called. The most natural thing would be to (call `close` automatically and) panic due to the programmer error (not calling `close`). If the default is switched to panic-in-drop=abort, and probably just if panic-in-drop becomes a thing libraries are expected to support, then the guideline should be expanded to say that failing to call `close` should either leak the error from `close` or leak the unclosed resource (and potentially log a warning, if available).)

https://github.com/rust-lang/api-guidelines/pull/263

**Comment by audunhalland** [comment]
A pattern I've seen several places is panicking in Drop for _RAII testing utilities_. E.g.

```rust
#[test]
fn test() {
    let verifier = ...;
    verifier.foo();
    verifier.bar();
}
```

The "verifier" executes a bunch of code in its Drop impl, with the intention of failing the current test if things were not OK.

**Comment by CAD97** [comment]
I can confirm that tracing does this in tracing-mock, as an example of a big project using this. The mocks panic on drop if an expected event does not happen.

For the test case, you *really* don't want to silently swallow errors in the case you forget to call `finalize`, because that will result in an incorrectly ineffective test. Taking down the entire test harness with an abort is also quite undesirable.

**Comment by yaahc** [comment]
> For the test case, you _really_ don't want to silently swallow errors in the case you forget to call `finalize`, because that will result in an incorrectly ineffective test. Taking down the entire test harness with an abort is also quite undesirable.

What is the problem with aborting the tests? I understand that this will cause problems with concurrent tests when you take down the whole harness, but I assume that these tests will run quickly. If an abort is intended to serve as a reminder to insert a 'finalize,' that seems like a reasonable trade-off to make.

**Comment by yaahc** [comment]
> Aborting in a test gives you absolutely no context about which test failed and how. The test harness swallows panic messages and only shows them after all tests have run. Aborting before that gives it no chance to print anything useful.

Ah, of course, I forgot that would suppress the output and make it difficult to figure out which test aborted. thank you

**Comment by programmerjake** [comment]
> Aborting in a test gives you absolutely no context about which test failed and how. The test harness swallows panic messages and only shows them after all tests have run. Aborting before that gives it no chance to print anything useful.

imho if it aborts due to panic in drop, that should be hook-able so the test crate can try to output the output for the aborting test

**Comment by CAD97** [comment]
Getting just the stacktrace is *enough* to determine which test failed, but still much less desirable than saying "test X failed" (and ideally, continuing to the other tests).

> but I assume that these tests will run quickly

Even if individual tests run quickly, the costs add up the more tests you run -- and in fact seeing multiple tests fail can help you identify where the problem is in the first place.

**Comment by programmerjake** [comment]
> Getting just the stacktrace is _enough_ to determine which test failed, but still much less desirable than saying "test X failed" (and ideally, continuing to the other tests).

assuming the stdout/stderr locks (idk if we have those when stdout is redirected) aren't held, that abort hook should be able to write everything in the buffer, not just a backtrace.

**Comment by bjorn3** [comment]
Every thread has a different stdout/stderr override. A global abort hook can't read those. Only a libtest specific abort hook could.

**Comment by programmerjake** [comment]
> Every thread has a different stdout/stderr override. A global abort hook can't read those. Only a libtest specific abort hook could.

the whole point of abort being hookable is that code can set the hook...can't libtest set the hook too?

the hook function should be able to read the thread local containing the current thread's output buffer

**Comment by kornelski** [comment]
Hooks are IMHO a poor design. They're shared mutable state. They're problematic when there's more than one thing in the whole program wanting to use them. There's not much that can be safely done inside a hook, especially bigger tasks like waiting for other tests and returning properly formatted output.

There is already a properly isolated, reliable, scoped hook for the failures: `catch_unwind`.

**Comment by programmerjake** [comment]
another idea: instead of aborting the whole process when it can't be unwound, just exit the thread and return the panic as the result of `join` -- essentially `mem::forget`-ing everything on the call stack.

this may not work out for things like scoped threads where the destructors are expected to be run.

**Comment by bjorn3** [comment]
> essentially mem::forget-ing everything on the call stack.

Deallocating the stack without calling the `Drop` impl for all pinned values on the stack breaks the pin invariant. Not deallocating the stack may not be possible depending on the OS and would be a huge memory leak in general.

**Comment by Amanieu** [comment]
> A pattern I've seen several places is panicking in Drop for _RAII testing utilities_. E.g.
> 
> ```rust
> #[test]
> fn test() {
>     let verifier = ...;
>     verifier.foo();
>     verifier.bar();
> }
> ```
> 
> The "verifier" executes a bunch of code in its Drop impl, with the intention of failing the current test if things were not OK.

Could this API be reworked to use a closure instead?

```rust
with_verifier(|verifier| {
    verifier.foo();
    verifier.bar();
});
```

That way the validation code can run after the closure if it executes successfully. As a bonus this also skip the validation if a panic occurred (which would trigger a double panic abort anyways).

**Comment by CAD97** [comment]
> Could this API be reworked to use a closure instead?

It (almost[^1]) always *can*, but actually doing so is usually undesirable because of the increased indentation.

[^1]: consider the case of `let mock = mock(); with_collector(mock.collector(), || { do_things(); drop(mock); do_things(); });` which drops the mock during a different closure callback. Though I think this is quite uncommon in practice, and an explicit drop can always be trivially replaced with an explicit close.

> As a bonus this also skip the validation if a panic occurred (which would trigger a double panic abort anyways).

Any test helper will (hopefully) be checking `thread::panicking()` already before doing validation/panicking itself.

And to the point of aborting in tests, the cases where tracing-mock accidentally does contain double panics are quite difficult to track down (due in part to stdout verbosity in the tests meant to help track down tracing failures, but which unfortunately aren't much help for tracking down *testing* failures.)

**Comment by joshtriplett** [comment]
We discussed this in the last couple of @rust-lang/lang meetings.

We are, generally, in favor of going ahead with this. However, we'd like to be able to point to a document that explains the plan, rationale, and rejected alternatives, because we expect to find ourselves explaining it regularly. (In particular, some discussion of why we're intentionally not stabilizing the `-Z` option to turn this back off.)

Could we get the skeleton of an RFC, focusing on those three elements (plan, rationale, alternatives)? Given such an RFC, we'll run the FCP on that, and once that goes through we're prepared to ship this.

**Comment by CAD97** [comment]
Since I've argued for both positions, my position refinement might be relevant:

I'm personally now fine with `panic = "unwind"` saying that panics *escaping* drops are always a panic-in-unwind style abort. *However,* I'd like to see `panic = "drop-unwind"` support implemented and available through cargo (even if still an unstable rustc/cargo feature) with at least a *plausible* path to stabilization (even if it's deferred to later) for the purpose of supporting tests.

Alternatively, the testing infrastructure can always use the abort-resilient strategy. It doesn't necessarily need to run every test in a separate process like the current `panic = "abort"` strategy, but I'd be less hesitant if the default testing strategy could capture an abort as a (single) test failure.

**Comment by CAD97** [comment]
I'd be wary of automatically changing from `panic = "unwind"` in debug/release to `panic = "drop-unwind"` in test, because if a panic escaping a drop is caught in a test, this could lead to the test passing but aborting in non test builds.

**Comment by nbdd0121** [comment]
I feel that the dicussion should be split into two aspects, the safety aspect and the size saving aspect.

I feel that we have other good alternatives to the safety aspect, e.g. a function-level toggle to make a function nounwind. Making panics in drop abort won't solve the safety problem as long as we want backward compatibility or type-level opt-outs (e.g. for `ScopeGuard`).

On the size saving aspect, I don't believe that's good enough reason to switch the default, especially it's a potentially breaking change. We don't just switch the default to `-C panic=abort` because it can bring size savings.

**Comment by CAD97** [comment]
And notably, there's a significant difference between

- "You don't need to worry about drops unwinding," and
- "Drops will never unwind by default, but can when `panic = "drop-unwind"`."

My position is that changing the default is fine and perhaps even desirable, but that `panic = "drop-unwind"` should still remain a configuration expected to be supported by resilient libraries. This may mean a few library CVEs for "library is not sound when used in non-default `panic = "drop-unwind"` compiler configuration," but I find that more agreeable than retroactively making panics escaping a [`defer!`](https://docs.rs/scopeguard/latest/scopeguard/macro.defer.html) abort where they don't currently without recourse.

It's currently somewhat reasonable to write a library that only guarantees functionality/soundness when `panic = "abort"`. It's generally not well received to publish such to crates-io, but it's fine to write code that relies on certain build configurations. As a lower-level language, this is a reasonable thing for users to expect to be supported. Code that requires `panic = "unwind"` and doesn't support `panic = "drop-unwind"` will be more prevalent than code which requires `panic = "abort"`, but it's also important to note that this isn't an ecosystem split, it's a *subset*, like (lacking) `#[no_std]` support.

I'm sympathetic to the soundness reasoning benefits of guaranteeing drop glue is `nounwind`. But even in C++ where they made the breaking change to make dtors `noexcept` by default, you can still opt out by using `noexcept(false)`. Though the difference is that C++ containers can much more easily say "requires dtors to be noexcept" than in Rust, where soundness under all inputs is provided by default.

I'll refine my position into a more proper supported argument once the RFC is drafted.

Is crater able to instrument crater to determine if programs/tests which currently do not abort (this *includes* fail by panic before the patch) are made to abort? A crater run classifying not just pass->fail but also panic->abort would do a significant amount for weighing the cost of changing the default. However, it should be noted that generally tests for published code should (hopefully) pass, and thus not exercise the failing paths (which is where panic in dtor is most likely to occur). We might still catch some, though, by tests for testing harnesses which `#[should_panic]`.

**Comment by RalfJung** [comment]
> It's currently somewhat reasonable to write a library that only guarantees functionality/soundness when panic = "abort". It's generally not well received to publish such to crates-io, but it's fine to write code that relies on certain build configurations. As a lower-level language, this is a reasonable thing for users to expect to be supported. Code that requires panic = "unwind" and doesn't support panic = "drop-unwind" will be more prevalent than code which requires panic = "abort", but it's also important to note that this isn't an ecosystem split, it's a subset, like (lacking) #[no_std] support.

This almost seems to argue for a way for libraries to declare which panic strategies they are compatible with?

**Comment by CAD97** [comment]
If we do decide to have a third panic strategy, it does seem useful. With the current split just being unwind/abort, the social pressure to support unwinding (or at the very least not cause UB on unwinding) in public libraries is probably enough, especially since the difference to conformance is mostly just sprinkling `AbortOnUnwindBomb`s around on the stack as necessary to plug holes.

**Comment by ChayimFriedman2** [comment]
> The primary motivation, I think, is changing the expectation for whether libraries are expected to handle Drop types that panic in drop, or whether libraries can assume that case won't happen.

Are there known footguns other than `catch_unwind()` with panicking payload? Because if not, we can just apply one of the proposed solutions to make it catch/abort just in this case.

**Comment by LegionMammal978** [comment]
I'd like to give my own two cents, even if this is change already a *fait accompli*. I've gathered that two main issues with the status quo are relevant here:

1. Since dropping happens implicitly, it is too easy to cause UB by dropping a user-supplied value in an `extern "C"` function, or any other language- or library-level `nounwind` context. This manifests in the panic-on-drop panic payload footgun, among other issues.
2. During an unwinding panic, a destructor that panics again immediately terminates the process. This can be undesirable in web servers and other contexts where threads should be isolated from each other.

Since this change doesn't resolve the second issue (personally speaking, it would be nice if we had a flag to allow stacking panics when `std` is available), I'll focus on the first.

There have been several comparisons between this proposed behavior and C++11's default-`noexcept` destructors. However, there are important differences between the semantics of Rust and C++ that make panicking `Drop` impls much less problematic than exception-throwing destructors.

The most major difference is Rust's move semantics. In Rust, you can move a value from a binding into a function, making that function responsible for dropping (or storing) the value. But in C++, every local variable will always have its destructor implicitly called at the end of its scope. There's absolutely no way to avoid the implicit destruction, apart from wrapping the value in an `std::optional` or similar. (Among other consequences, this means that move operations in C++ must always leave a valid sentinel value.)

In other words, C++ functions must implicitly destroy *all* their owned variables, whereas Rust functions only implicitly drop those variables that have not been moved somewhere else. In particular, Rust allows users to drop every significant value explicitly, by moving them into the appropriately named `drop()` function.

Another difference is between the meaning of C++'s exceptions and Rust's panics on a semantic level. In Rust, a panic is considered an irrecoverable error: something happened which you think should never happen, or which you have no way of ignoring or correcting, so the current task (perhaps the whole process, or perhaps only the current thread) must be canceled without further ado. But C++ primarily uses exceptions to express ordinary error conditions, which would just be `Result`s in Rust. The built-in assertions for sanity checks don't throw exceptions, but abort the whole program instead.

From this perspective, it makes sense why destructors in C++ should be `noexcept`. Why should destroying an object do the equivalent of returning a `Result`? How should containers continue freeing their memory after one destructor fails? But a panicking `Drop` impl has a different semantic meaning: it means that containers should try their best to clean up the remaining memory they own, so that the current task can be canceled without any resource leaks. If another `Drop` impl panics in the process, then there's not much more that can be done.

Together, I believe these differences give us more freedom than C++ to allow panicking `Drop` impls. While C++ only has two modes of error reporting, exceptions and aborts, Rust has three: `Result`s, unwinding panics, and aborting panics. This change would collapse many unwinding panics into aborting panics, which would be detrimental to web servers and other processes that have isolated threads. And since Rust allows us to explicitly move values into other functions, users can have fine-grained control over exactly when variables are dropped.

Therefore, I am in favor of a solution like one proposed by @danielhenrymantilla on the community Discord server: Create an allow-by-default lint that triggers on every significant drop from variables falling out of scope. Then, users writing unsafe code can `#[warn(...)]` or `#[error(...)]` this lint on every function that is sensitive to panics, and we can recommend its use in the nomicon and other unsafe-code resources. (These uses would include nearly every `extern "C"` function, unsafe collection `Drop` impls, and invariant-sensitive `unsafe` functions in general.) The lint could be silenced by explicitly `drop()`ping the values, or otherwise transferring their ownership out of the function. We can keep `-Z panic-on-drop=abort` available for the performance benefits (much like `-C panic=abort` but less drastic), but we should always set the default as `-Z panic-on-drop=unwind`.

**Comment by ChayimFriedman2** [comment]
> "significant" drop here means "has drop glue," "more than nothing (`forget`)," or "runs _some_ `Drop::drop` code."



> My apologies; by a "significant drop", I mean any drop that calls a `Drop` impl, or approximately, dropping any type `T` where [`core::mem::needs_drop::<T>()`](https://doc.rust-lang.org/core/mem/fn.needs_drop.html). This is somewhat inspired by [`clippy::significant_drop_in_scrutinee`](https://rust-lang.github.io/rust-clippy/master/#significant_drop_in_scrutinee), although I should probably use another name to avoid confusing the concepts.

This is what I thought; I just wanted to make sure you didn't mean something like "runs _user_ code on drop".

> Making std types special as "not user code" and therefore "safe" to drop (if they only contain std types) is unfair to third party libraries and further privileges std.

I didn't mean to implement this only for std types. I want an (allow-by-default) lint that warns when you run untrusted code, i.e. user code. As long as you know the types everything is fine ([unsafe Rust can trust known safe code](https://doc.rust-lang.org/nomicon/safe-unsafe-meaning.html)). Generics are indeed a problem, but even using heuristics will be a big help.

**Comment by CAD97** [comment]
Rather than specifying "user code" (from a compiler perspective, that's *any* Rust code not emitted by the compiler), it's better to say "upstream" or "downstream" for the relationship of the library dependency graph.

There should still be a lint for implicit drop glue of upstream types, but I do agree that *if such a lint is added*, splitting it into two tiers of downstream and all types would indeed be useful.

**Comment by nbdd0121** [comment]
> Also, @nbdd0121: abort on unwind can be made even simpler, skipping the need to `forget` with a cheap runtime check:
> 
> ```rust
> impl Drop for AbortOnUnwind {
>     fn drop(&mut self) {
>         if std::thread::panicking() { panic!("unwound through nounwind context") }
>     }
> }
> ```

I think it's desirable in the future to allow multiple concurrent panics -- as long as the inner panic is caught and does not escape. This code will disallow nested panics.

Also, checking `std::thread::panicking` would not protect your against a foreign exception; `std::thread::panicking()` would return false when, for example, a C++ exception causes the current in-progress unwind.

**Comment by nbdd0121** [comment]
> C++ exceptions crossing Rust frames with drop glue are already UB, and there is no current plan to make them not UB. 

That's not true with `C-unwind`.

> `panic!` was an option you gave and the one I chose for the example; you can just as easily use `abort`. 

No, I mean your code would abort when it is used *while unwinding is already in place*, not only when *a new unwind propagates out from the function body*.

> But this is off topic noise in an already noisy thread.

Well, I think this is on-topic, since other ways to prevent the footgun would be alternative solutions to the proposed approach.

**Comment by CAD97** [comment]
> > C++ exceptions crossing Rust frames with drop glue are already UB, and there is no current plan to make them not UB.
> 
> That's not true with `C-unwind`.

Ah, apologies, I misremembered the [section about forced unwinds](https://rust-lang.github.io/rfcs/2945-c-unwind-abi.html#frame-deallocation-and-forced-unwinding) as applying to *all* foreign unwinds.

**Comment by Amanieu** [comment]
I wrote an RFC to argue for turning `-Z panic-in-drop=unwind` on by default: https://github.com/rust-lang/rfcs/pull/3288

**Comment by RalfJung** [comment]
I assume you mean "=abort"?

**Comment by Amanieu** [comment]
Oops, fixed.

**Comment by nikomatsakis** [comment]
There is now an RFC, I don't think we ever had the meeting, going to close this meeting request.
